### ISSUE TITLE
Implement Crafting effects

### ISSUE THREAD

**Issue by smartaleq** [smartaleq/DwarfCraft_orig#16]
Using onCraftEvent or a workaround.

**Comment by smartaleq** [comment]
possible workaround by using https://github.com/nodren/minecraft-bukkit-craftdispenser/tree/master/src/com/echo28/bukkit/craftdispenser

**Comment by RCarretta** [comment]
Have you looked at how other addons are doing this? There are several out there that implement new recipes, etc. I imagine they would be doing something similar to what we are looking to do.

**Comment by smartaleq** [comment]
https://github.com/fullwall/Cookbook/tree/master/com/fullwall/cookbook

using that as source for our purposes. will check if I should put on server and override methods or just steal the algorithms and attribute.

**Comment by smartaleq** [comment]
code written, gonna drive home and push, test, etc.

source is pretty elegantly simple, however it does call server methods directly, which means it will eventually need to be fixed up on a craftbukkit update.

**Comment by RCarretta** [comment]
if you haven't, please pull the server calls out into separate functions, so when the code is pulled into bukkit we can merely remove those functions and update the callers, rather than remodeling the calling function.

**Comment by smartaleq** [comment]
wish i could, but it would be a lot of work to fix up, i think. snippet:

this is used for the built-in recipes, appears ~50 times.
new itemstack is a server call, not a cb.ItemStack

this.addShaped(new ItemStack(Item.PAPER, 3), new Object[] { "###",Character.valueOf('#'), Item.SUGAR_CANE });

another sample of server-call code.

ContainerWorkbench containerBench = null;
try {containerBench = (ContainerWorkbench) entityPlayer.activeContainer;

//another example. I believe the field "b" is the output item stack on a crafting table inventory object.
    ItemStack result = ((InventoryCraftResult) containerBench.b)
                    .getContents()[0];

**Comment by RCarretta** [comment]
As far as I'm concerned, this feature should be dropped for v1.0 and be revisited when there are adequate CraftBukkit hooks and events available.

The best way I can see to do this involves creating a CraftingManager instance for each player where the material cost and ouput quantities (and items) can be declared. These instances would be updated whenever the player logged in or trained a skill, and a list (or more likely HashMap) would be maintaned mapping players->CraftingManagers. The problem exists in associating the player to the CraftingManager instance, and instantiating the CraftingManager itself - from what I can tell there is nowhere plugin code will be executed based on crafting events.

There are 3 ways I can conceive of to do this:
1.) fullwall's implmentation - create a thread that continuously monitors the player's inventory, and 'intervenes' when it sees what it wants. This is, in my opinion, an ugly approach, and one I consider to be barely functional. It is riddled with race conditions, in that a CPU context switch at any point within some of these methods will potentially cause nondeterministic effects on a player's inventory. Additionally, it causes unnecessary burden on the CPU due to the nature of the thread needing to run continuously to 'monitor' and not blocking for some input or event. 

2.) Use the Java instrumentation interface to redefine the relevant net.minecraft.server classes. This would require external .class files to ship with the 'product', and for the user to have external tools (JDK, and an additional command line argument when launching the program). Not tenable imho.

3.) Edit craftbukkit directly, recompile, and ship a custom craftbukkit with the plugin. This is undesirable for obvious reasons, not the least of which is maintenance.

Either way, when the appropriate CraftBukkit events are released, any 3 of these solutions would need to be entirely ripped out, scrapped, and rewritten.

**Comment by smartaleq** [comment]
this is working. Rebalanced skills and implementing damage values.
